In [ ]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [ ]:
# To get the details about the dataset, please visit
# https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [ ]:
d={}
for i in df['Team'].unique():
  x=df[(df['Team']==i)]['Total Attempts'].sum()
  y=df[(df['Team']==i)]['On Target'].sum()
  d[i]=(round(y/x *100,2))
sorted(d.items(),key=lambda x:x[1],reverse=True)

[('Costa Rica', 54.55),
 ('Cameroon', 51.85),
 ('Ecuador', 48.15),
 ('Argentina', 46.15),
 ('Brazil', 45.56),
 ('England', 45.0),
 ('Portugal', 40.32),
 ('Ghana', 40.0),
 ('Netherlands', 39.02),
 ('Korea Republic', 36.73),
 ('Australia', 36.0),
 ('Mexico', 34.88),
 ('France', 34.65),
 ('Germany', 34.33),
 ('Croatia', 33.73),
 ('Spain', 32.69),
 ('Belgium', 32.35),
 ('Serbia', 32.26),
 ('Iran', 31.43),
 ('Uruguay', 31.25),
 ('United States', 31.11),
 ('Saudi Arabia', 31.03),
 ('Senegal', 30.77),
 ('Denmark', 30.56),
 ('Switzerland', 30.56),
 ('Japan', 30.23),
 ('Wales', 29.17),
 ('Qatar', 28.57),
 ('Morocco', 28.33),
 ('Tunisia', 26.67),
 ('Poland', 25.0),
 ('Canada', 17.65)]

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [ ]:
df['Team'].value_counts().sort_values(ascending=False).rank(method='first')

Team
Morocco           29.0
Argentina         30.0
France            31.0
Croatia           32.0
England           25.0
Brazil            26.0
Netherlands       27.0
Portugal          28.0
Korea Republic    17.0
Spain             18.0
Senegal           19.0
United States     20.0
Australia         21.0
Switzerland       22.0
Japan             23.0
Poland            24.0
Ecuador            1.0
Iran               2.0
Wales              3.0
Saudi Arabia       4.0
Denmark            5.0
Tunisia            6.0
Mexico             7.0
Cameroon           8.0
Germany            9.0
Costa Rica        10.0
Qatar             11.0
Canada            12.0
Ghana             13.0
Belgium           14.0
Uruguay           15.0
Serbia            16.0
Name: count, dtype: float64

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [ ]:
df.columns

Index(['Sl. No', 'Match No.', 'Team', 'Against', 'Group', 'Goal',
       'Possession (%)', 'Inside Penalty Area', 'Outside Penalty Area',
       'Assists', 'Total Attempts', 'On Target', 'Off Target',
       'Target in Penalty', 'Target from Outside', 'Left Channel',
       'Left Inside Channel', 'Central Channel', 'Right Inside Channel',
       'Right Channel', 'Receptions MD', 'Receptions D',
       'Attempted Line Breaks', 'Completed Line Breaks',
       'Attempted Defensive Line Breaks', 'Completed Defensive Line Breaks',
       'Yellow Cards', 'Red Cards', 'Fouls Against', 'Offsides', 'Passes',
       'Passes Completed', 'Crosses', 'Crosses Completed', 'Corners',
       'Free Kicks', 'Penalties Scored', 'Pts'],
      dtype='object')

In [ ]:
#df.info()
#df.describe()
df.isnull().sum()
df.drop_duplicates(inplace=True)
df.drop(columns=['Team'])

,Sl. No,Match No.,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Fram,F,0,55,0,0,0,13,1,6,8,5,10,4,6,6,19,74,15,141,95,18,11,1,0,11,3,583,518,22,1,3,15,0,0
124,125,63,Morocco,F,2,45,2,0,2,14,4,8,7,7,20,8,3,2,7,106,15,164,114,23,12,0,0,13,2,491,430,21,3,6,13,0,3
125,126,63,Croatia,F,1,45,1,0,0,7,2,5,5,2,13,1,3,7,16,75,10,150,97,14,8,2,0,11,2,494,428,20,5,3,15,0,0
126,127,64,France,C,3,46,3,0,1,21,9,9,13,8,13,6,8,9,9,163,28,249,172,40,24,4,0,26,4,648,544,20,4,6,22,5,3
127,128,64,Argentina,D,3,40,3,0,1,10,5,3,7,3,15,7,5,4,12,69,9,179,107,14,9,3,0,19,4,516,419,24,3,5,28,4,0

### `Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [ ]:
df['Rank']=df['Team'].rank(method='first')
df['Rank']=df["Rank"].astype(np.int16)
df.set_index('Rank',inplace=True)
df.sort_index()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
Rank,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,9,5,Argentina,Saudi Arabia,C,1,51,1,0,0,14,6,6,10,4,12,4,5,8,18,91,27,195,127,10,8,0,0,7,10,593,525,36,15,9,21,1,0
2,47,24,Argentina,Mexico,C,2,50,1,1,2,5,2,3,2,3,10,6,2,4,12,89,2,150,100,10,5,1,0,15,2,533,464,14,2,4,23,0,3
3,78,39,Argentina,Poland,C,2,67,1,1,2,25,13,8,10,15,25,8,7,10,26,150,36,141,126,20,16,1,0,11,0,862,814,22,5,9,5,0,3
4,99,50,Argentina,Australia,C,2,53,2,0,1,14,5,7,11,3,15,6,11,2,17,127,8,181,135,16,8,0,0,8,4,711,635,6,1,1,15,0,3
5,116,58,Argentina,Netherlands,C,2,44,2,0,1,15,6,8,5,10,7,7,13,6,17,104,7,203,122,24,8,8,0,18,2,603,511,16,4,8,30,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,64,32,Uruguay,Portugal,H,0,35,0,0,0,10,3,6,6,4,13,8,4,5,9,94,6,150,86,17,11,2,0,16,0,390,306,18,5,2,13,0,0
125,90,45,Uruguay,Ghana,H,2,39,2,0,1,12,7,5,7,5,7,2,13,3,17,186,14,186,124,24,14,3,0,11,2,446,361,15,4,2,20,0,3
126,8,4,Wales,United States,B,1,39,1,0,0,7,3,3,5,2,7,2,5,2,7,73,9,174,103,17,8,2,0,10,1,409,321,15,6,3,15,1,1
127,33,17,Wales,Iran,B,0,51,0,0,0,10,3,4,5,5,18,3,8,11,13,101,13,208,129,17,8,1,1,9,2,508,413,20,5,2,12,0,1
128,69,35,Wales,England,B,0,33,0,0,0,7,1,3,1,6,7,1,2,0,4,46,1,104,55,4,1,2,0,16,1,325,261,4,1,1,10,0,0

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [ ]:
titanic_df1 = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv")
titanic_df2 = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv")
titanic_df1.dropna(subset=['Age'],inplace=True)
titanic_df2['Age'] = titanic_df2['Age'].fillna(20)

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

In [ ]:
matches=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv")

### `Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [ ]:
df = matches[~matches.WinningTeam.isna()]
new_df = pd.DataFrame()
teams = df.Team1.unique()
data = []
for team in teams:
    played = df[(df.Team1 == team) | (df.Team2 == team)].shape[0]
    wins = df[df.WinningTeam == team].shape[0]
    home_win = df[(df.WinningTeam == team) | (df.Team1 == team)].shape[0] / df[df.Team1 == team].shape[0] * 100
    away_win = df[(df.WinningTeam == team) | (df.Team2 == team)].shape[0] / df[df.Team2 == team].shape[0] * 100
    data.append([team, played, wins/played*100, home_win, away_win])
new_df[["Team", "Matches Played", "Win Percentage", "Home Win Percentage", "Away Win Percentage"]] = data
new_df.sort_values("Win Percentage", inplace=True, ascending=False)
new_df

,Team,Matches Played,Win Percentage,Home Win Percentage,Away Win Percentage
5,Gujarat Titans,16,75.0,214.285714,144.444444
12,Rising Pune Supergiant,16,62.5,171.428571,155.555556
6,Lucknow Super Giants,15,60.0,125.0,200.0
4,Chennai Super Kings,208,58.173077,150.45045,167.010309
3,Delhi Capitals,63,57.142857,172.413793,144.117647
9,Mumbai Indians,231,56.709957,158.928571,154.621849
7,Kolkata Knight Riders,223,51.121076,155.238095,147.457627
0,Rajasthan Royals,190,50.526316,152.808989,148.514851
2,Sunrisers Hyderabad,152,49.342105,156.521739,143.373494
1,Royal Challengers Bangalore,223,48.878924,139.02439,161.0
8,Punjab Kings,28,46.428571,133.333333,170.0
10,Kings XI Punjab,190,46.315789,148.913043,143.877551
13,Gujarat Lions,30,43.333333,150.0,135.714286
17,Kochi Tuskers Kerala,14,42.857143,142.857143,142.857143
11,Delhi Daredevils,159,42.138365,134.52381,150.666667
16,Deccan Chargers,75,38.666667,141.025641,136.111111
14,Rising Pune Supergiants,14,35.714286,142.857143,128.571429
15,Pune Warriors,45,26.666667,126.086957,127.272727

### `Q-7:` Venues with most "no result" matches.

In [ ]:
matches[matches['WonBy']=='NoResults']['Venue'].value_counts().sort_values(ascending=False).head(1)

Venue
M Chinnaswamy Stadium    2
Name: count, dtype: int64

### `Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [ ]:
# code here
def getPlayers(l):
    return pd.Series(list(map( lambda x: x.strip("'"), l.lstrip("'[").rstrip("]'").split(", "))))

df_final = matches[matches["MatchNumber"] == "Final"]
playerSeries = pd.Series()
for player_list in df_final.Team1Players:
    x = getPlayers(player_list)
    playerSeries = playerSeries.append(x)
for player_list in df_final.Team2Players:
    x = getPlayers(player_list)
    playerSeries = playerSeries.append(x)
playerSeries.value_counts().head()

AttributeError: 'Series' object has no attribute 'append'

### `Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [ ]:
# code here
def matches_played(df, team):
    return df[(df.Team1 == team) | (df.Team2 == team)].shape[0]
def matches_won(df, team):
    return df[df.WinningTeam == team].shape[0]
def matches_no_result(df, team):
    return df[((df.Team1 == team) | (df.Team2 == team)) & (df.WinningTeam.isnull())].shape[0]

def point_table(season):
    df = matches[matches.Season == season]
    new_df = pd.DataFrame()
    new_df['Team Name'] = df.Team1.unique()
    new_df["Matches Played"] = new_df["Team Name"].apply(lambda x: matches_played(df, x))
    new_df["Matches Won"] = new_df["Team Name"].apply(lambda x: matches_won(df, x))
    new_df["No Result"] = new_df["Team Name"].apply(lambda x: matches_no_result(df, x))
    new_df["Points"] = new_df["Matches Won"]*2 + new_df["No Result"]
    new_df.sort_values("Points", ascending = False, inplace=True)
    new_df.set_index("Team Name", inplace=True)
    return new_df
point_table("2022")

                             Matches Played  Matches Won  No Result  Points
Team Name
Gujarat Titans                           16           12          0      24
Rajasthan Royals                         17           10          0      20
Royal Challengers Bangalore              16            9          0      18
Lucknow Super Giants                     15            9          0      18
Delhi Capitals                           14            7          0      14
Punjab Kings                             14            7          0      14
Sunrisers Hyderabad                      14            6          0      12
Kolkata Knight Riders                    14            6          0      12
Chennai Super Kings                      14            4          0       8
Mumbai Indians                           14            4          0       8

### `Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [ ]:
# code here
def point_table_extension(season):
    df3 = point_table(season)
    df = matches[matches.Season == season].copy()
    df3["SeasonPosition"] = df3.Points.rank(ascending=False, method= 'first').astype('object')
    df["LoosingTeam"] = df[df.WinningTeam == df.Team1]["Team2"].append(df[df.WinningTeam == df.Team2]["Team1"])
    final = df[df["MatchNumber"] == "Final"]
    wining_team = final.WinningTeam.values[0]
    runner = final.LoosingTeam.values[0]
    df3.at[wining_team, "SeasonPosition"]="Winner"
    df3.at[runner, "SeasonPosition"]="Runner"
    q = df[df["MatchNumber"] == "Qualifier 2"]
    e = df[df["MatchNumber"] == "Eliminator"]
    third = q.LoosingTeam.values[0]
    fourth = e.LoosingTeam.values[0]
    df3.at[third, "SeasonPosition"] = "Third"
    df3.at[fourth, "SeasonPosition"] = "Fourth"
    return df3
point_table_extension("2022")

AttributeError: 'Series' object has no attribute 'append'