# Tuple


###`Q1:` Join Tuples if similar initial element
While working with Python tuples, we can have a problem in which we need to perform concatenation of records from the similarity of initial element. This problem can have applications in data domains such as Data Science.

For eg.
```
Input  : test_list = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13)]
Output : [(5, 6, 7, 8), (6, 10), (7, 13)]
```

In [49]:
t=[(5, 6), (5, 7), (5, 8), (6, 10), (7, 13)]

In [63]:
i=0
tt=[]
while i<5:
  k=i
  s=list(t[i])
  for j in t[k+1:]:
    if t[i][0]==j[0]:
      s.extend(j)
      i=i+1
  i=i+1
  tt.append(set(s))
tt

[{5, 6, 7, 8}, {6, 10}, {7, 13}]

###`Q2:` Multiply Adjacent elements (both side) and take sum of right and lest side multiplication result.


For eg.
```
The original tuple : (1, 5, 7, 8, 10)
Resultant tuple after multiplication :

(1*5, 1*5+5*7, 7*5 + 7*8, 8*7 + 8*10, 10*8) -> (5, 40, 91, 136, 80)

output-(5, 40, 91, 136, 80)
```

In [ ]:
t = (1, 5, 7, 8, 10)
new_t=[]
new_t.append(t[0]*t[1])
for i in range(1,len(t)-1):
  new_t.append((t[i-1] *t[i] ) + (t[i]* t[i+1]))
new_t.append(t[-1]*t[-2])
new_t

[5, 40, 91, 136, 80]

###`Q3`: Check is tuples are same or not?
Two tuples would be same if both tuples have same element at same index
```
t1 = (1,2,3,0)
t2 = (0,1,2,3)

t1 and t2 are not same
```

In [ ]:
t1 = (1,2,3,0)
t2 = (0,1,2,3)
t1==t2

False

In [ ]:
for i,j in (zip(t1,t2)):
  flag=True
  if i!=j:
    flag=False
if flag==True:
  print('same')
else:
  print('not same')

not same

###`Q4`: Count no of tuples, list and set from a list
```
list1 = [{'hi', 'bye'},{'Geeks', 'forGeeks'},('a', 'b'),['hi', 'bye'],['a', 'b']]

```
`Output:`

```
List-2
Set-2
Tuples-1
```

In [ ]:
list1 = [{'hi', 'bye'},{'Geeks', 'forGeeks'},('a', 'b'),['hi', 'bye'],['a', 'b']]
listt=0
sett=0
Tuples=0

for i in list1:
  if isinstance(i,list):  ## Can also be solved with the help of the type but isinstance is used with any custom class as well
    listt = listt + 1
  if isinstance(i,set):
    sett = sett + 1
  if isinstance(i,tuple):
    Tuples = Tuples + 1
print("List-{}\nSet-{}\nTuples-{}".format(listt,sett,Tuples))

List-2
Set-2
Tuples-1

###`Q5`: Shortlist Students for a Job role
Ask user to input students record and store in tuples for each record. Then Ask user to input three things he wants in the candidate- Primary Skill, Higher Education, Year of Graduation.

Show every students record in form of tuples if matches all required criteria.

It is assumed that there will be only one primry skill.

If no such candidate found, print `No such candidate`

`Input:`
```
Enter No of records- 2
Enter Details of student-1
Enter Student name- Manohar
Enter Higher Education- B.Tech
Enter Primary Skill- Python
Enter Year of Graduation- 2022
Enter Details of student-2
Enter Student name- Ponian
Enter Higher Education- B.Sc.
Enter Primary Skill- C++
Enter Year of Graduation- 2020

Enter Job Role Requirement
Enter Skill- Python
Enter Higher Education- B.Tech
Enter Year of Graduation- 2022
```

`Output`
```
('Manohar', 'B.tech', 'Python', '2022')
```

In [ ]:
students = []
num = int(input('enter the number of applicants'))
for i in range(num):
  print('Enter details of',i+1,'applicant:')
  name = input('enter name')
  h_ed = input('enter higher education')
  p_skill = input('enter primary skill')
  yog = input('enter year of graduation')

  students.append((name,h_ed,p_skill,yog))

required_skill = input('enter required skill')
required_hed = input('enter required higher education')
required_yog = input('enter required year of graduation')

flag = False
for i in students:
  if i[1] == required_hed and i[2] == required_skill and i[3] == required_yog:
    print(i)
    flag = True

if flag == False:
  print('No such candidates')

Enter details of 1 applicant:

# Set

###`Q1:` Write a program to find set of common elements in three lists using sets.
```
Input : ar1 = [1, 5, 10, 20, 40, 80]
        ar2 = [6, 7, 20, 80, 100]
        ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

Output : [80, 20]
```

In [ ]:
ar1 = [1, 5, 10, 20, 40, 80]
ar2 = [6, 7, 20, 80, 100]
ar3 = [3, 4, 15, 20, 30, 70, 80, 120]
set(ar1).intersection(set(ar2)).intersection(set(ar3))

{20, 80}

###`Q2:` Write a program to count unique number of vowels using sets in a given string. Lowercase and upercase vowels will be taken as different.

`Input:`
```
Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
```
`Output:`
```
No of unique vowels-6
```

In [9]:
Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
s=set()
for i in Str1:
  if i in ['a','e','i','o','u','A','E','O','I','U']:
    s.add(i)
print(len(s))

6

### `Q3:` Write a program to Check if a given string is binary string of or not.

A string is said to be binary if it's consists of only two unique characters.

Take string input from user.

```
Input: str = "01010101010"
Output: Yes

Input: str = "1222211"
Output: Yes

Input: str = "Campusx"
Output: No
```

In [ ]:
def is_binary_string(s):
    unique_chars = set(s)

    if len(unique_chars) != 2:
        return False

    for char in unique_chars:
        if char not in ['0', '1']:
            return False

    return True

# Taking input from the user
user_input = input("Enter a string: ")

### `Q4`: find union of n arrays.

**Example 1:**

Input:
```bash
[[1, 2, 2, 4, 3, 6],
 [5, 1, 3, 4],
 [9, 5, 7, 1],
 [2, 4, 1, 3]]
```

Output:

```bash
[1, 2, 3, 4, 5, 6, 7, 9]
```

In [ ]:
s=set()
for i in list1:
  for j in i:
    s.add(j)
s

### `Q5`: Intersection of two lists. Intersection of two list means we need to take all those elements which are common to both of the initial lists and store them into another list. Only use using **list-comprehension**.

**Example 1:**

Input:
```bash
lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
```

Output:
```bash
[9, 10, 4, 5]
```

**Example 2:**

Input:
```bash
lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
```

Output:
```bash
[9, 11, 26, 28]
```

In [ ]:
st1 = [15, 9, 10, 56, 23, 78, 5, 4, 9]
lst2 = [9, 4, 5, 36, 47, 26, 10, 45, 87]
list(set([i for i in st1 if i in lst2]))

# Dictionary

### `Q1`: Key with maximum unique values

Given a dictionary with values list, extract key whose value has most unique values.

**Example 1:**

Input:

```bash
test_dict = {"CampusX" : [5, 7, 9, 4, 0], "is" : [6, 7, 4, 3, 3], "Best" : [9, 9, 6, 5, 5]}
```

Output:
```bash
CampusX
```

**Example 2:**

Input:
```bash
test_dict = {"CampusX" : [5, 7, 7, 7, 7], "is" : [6, 7, 7, 7], "Best" : [9, 9, 6, 5, 5]}
```

Output:
```bash
Best
```

In [ ]:
test_dict = {"CampusX" : [5, 7, 9, 4, 0], "is" : [6, 7, 4, 3, 3], "Best" : [9, 9, 6, 5, 5]}
new_d={}
for i,j in test_dict.items():
  new_d[i]=len(set(j))

max_values=[]
for i in new_d.values():
  max_values.append(i)

for i,j in new_d.items():
  if j==max(max_values):
    print(i)

### `Q2`: Replace words from Dictionary. Given String, replace it’s words from lookup dictionary.

**Example 1:**

Input:

```bash
test_str = 'CampusX best for DS students.'
repl_dict = {"best" : "is the best channel", "DS" : "Data-Science"}
```

Output:

```bash
CampusX is the best channel for Data-Science students.
```

**Example 2:**

Input:
```bash
test_str = 'CampusX best for DS students.'
repl_dict = {"good" : "is the best channel", "ds" : "Data-Science"}
```

Output:
```bash
CampusX best for DS students.
```

In [ ]:
new_str=[]
for i in test_str.split():
  if i in repl_dict.keys():
    new_str.append(repl_dict[i])
  else:
    new_str.append(i)
' '.join(new_str)

### `Q3`: Convert List to List of dictionaries. Given list values and keys list, convert these values to key value pairs in form of list of dictionaries.

**Example 1:**

Input:
```bash
test_list = ["DataScience", 3, "is", 8]
key_list = ["name", "id"]
```

Output:

```bash
[{'name': 'DataScience', 'id': 3}, {'name': 'is', 'id': 8}]
```

**Example 2:**

Input:
```bash
test_list = ["CampusX", 10]
key_list = ["name", "id"]
```

Output:

```bash
[{'name': 'CampusX', 'id': 10}]
```

In [ ]:
test_list = ["DataScience", 3, "is", 8]
key_list = ["name", "id"]
l=[]
k=0
for i in range(int((len(test_list)/len(key_list)))):
  d={}
  for j in range(len(key_list)):
    d[key_list[j]]=test_list[k]
    k=k+1
  l.append(d)
l

### `Q4`: Convert a list of Tuples into Dictionary.

**Example 1:**

Input:
```bash
[("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
```

Output:
```bash
{'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}
```

**Example 2:**

Input:
```bash
[('A', 1), ('B', 2), ('C', 3)]
```

Output:
```bash
{'A': [1], 'B': [2], 'C': [3]}
```

In [12]:
t=[("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
d={}
for i in t:
  d[i[0]]=[i[1]]
d

{'akash': [10],
 'gaurav': [12],
 'anand': [14],
 'suraj': [20],
 'akhil': [25],
 'ashish': [30]}

### `Q5`: Sort Dictionary key and values List.

**Example 1:**

Input:

```bash
{'c': [3], 'b': [12, 10], 'a': [19, 4]}
```

Output:

```bash
{'a': [4, 19], 'b': [10, 12], 'c': [3]}
```

**Example 2:**

Input:

```bash
{'c': [10, 34, 3]}
```

Output:

```bash
{'c': [3, 10, 34]}
```

In [22]:
d={'a': [4, 19], 'b': [10, 12], 'c': [3]}
d_n={}
for i,j in d.items():
  d_n[i]=sorted(j)
d_n

{'a': [4, 19], 'b': [10, 12], 'c': [3]}

In [19]:
d={'c': 5, 'b': 6, 'a': 10}
sorted(d.items(),key=lambda x:x[1],reverse=True)

[('a', 10), ('b', 6), ('c', 5)]

In [20]:
d={'c': 5, 'b': 6, 'a': 10}
sorted(d.items(),key=lambda x:x[0])

[('a', 10), ('b', 6), ('c', 5)]