###`Problem 1:` Combine two lists index-wise(columns wise)

Write a program to add two lists index-wise. Create a new list that contains the 0th index item from both the list, then the 1st index item, and so on till the last element. any leftover items will get added at the end of the new list.

`Given List:`
```
list1 = ["M", "na", "i", "Kh"]
list2 = ["y", "me", "s", "an"]
```

`Output:`
```
[['M','y'], ['na', me'], ['i', 's'], ['Kh', 'an']]
```

In [ ]:
list1 = ["M", "na", "i", "Kh"]
list2 = ["y", "me", "s", "an"]
new_list=[]
for i in range(len(list1)):
  local_list = [list1[i],list2[i]]
  new_list.append(local_list)
print(new_list)

[['M', 'y'], ['na', 'me'], ['i', 's'], ['Kh', 'an']]

### `Problem 2:` Add new item to list after a specified item
Write a program to add item 7000 after 6000 in the following Python List
```
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
```
`Output:`
```
[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]
```

In [ ]:
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
list1.insert(1,7000)
list1

[10, 7000, 20, [300, 400, [5000, 6000], 500], 30, 40]

###`Problem 3:` Update no of items available

Suppose you are given a list of candy and another list of same size representing no of items of respective candy.

i.e -  
```
candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
no_of_items = [10,20,34,74,32]
```

Write a program to show no. of items of each candy type.

`Output:`

```
Jelly Belly-10
Kit Kat-20
Double Bubble-34
Milky Way-74
Three Musketeers-32

```

In [ ]:
candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
no_of_items = [10,20,34,74,32]
for i in range(len(candy_list)):
  print("{}-{}".format(candy_list[i],no_of_items[i]))

Jelly Belly-10
Kit Kat-20
Double Bubble-34
Milky Way-74
Three Musketeers-32

###`Problem 4:` Running Sum on list
Write a program to print a list after performing running sum on it.

i.e:

`Input:`
```
list1 = [1,2,3,4,5,6]
```
`Output:`
```
[1,3,6,10,15,21]
```

In [ ]:
list1=list(map(int,input('').split(',')))
new_list1=[]
summ=0
for i,j in enumerate(list1):
  summ=summ+list1[i]
  new_list1.append(summ)
new_list1

1,2,3,4

[1, 3, 6, 10]

In [ ]:
eval(input())

[1,211,3]

[1, 211, 3]

###`Problem 5:` You are given a list of integers. You are asked to make a list by running through elements of the list by adding all elements greater and itself.

i.e. Say given list is `[2,4,6,10,1]`
resultant list will be `[22,20,10,23]`.

For 1st element `2` ->> these are greater `(4+6+10)` values and `2` itself so on adding becomes `22`.

For 2nd element `4` ->> greater elements are `(6, 10)` and `4` itself, so on adding `20`

like wise for all other elememts.

`[2,4,6,10,1]`-->`[22,20,16,10,23]`

In [ ]:
list1=[2,4,6,10,1]
new_list=[]
for i in list1:
  local_list=[]
  for j in (list1):
    if i<=j:
      local_list.append(j)
  new_list.append(sum(local_list))
print(new_list)

[22, 20, 16, 10, 23]

###`Problem 6:` Find list of common unique items from two list. and show in increasing order

`Input`

```
num1 = [23,45,67,78,89,34]
num2 = [34,89,55,56,39,67]
```

`Output:`
```
[34, 67, 89]
```

In [ ]:
num1 = [23,45,67,78,89,34]
num2 = [34,89,55,56,39,67]
new_list=[]
for i in num1:
  for j in num2:
    if i==j:
      new_list.append(i)
print(sorted(new_list))

[34, 67, 89]

###`Problem 7:` Sort a list of alphanumeric strings based on product value of numeric character in it. If in any string there is no numeric character take it's product value as 1.

`Input:`
```
['1ac21', '23fg', '456', '098d','1','kls']
```

`Output:`
```
['456', '23fg', '1ac21', '1', 'kls', '098d']

```

In [ ]:
list1=['1ac21', '23fg', '456', '098d','1','kls']
d={}
for i in list1:
  if len(i)>1:
    if i.isalnum():
      prod=1
      for j in i:
        if j.isdigit():
          prod=prod*int(j)
      d[i]=prod
    else:
      d[i]=0
  else:
    if i.isdigit():
      d[i]=1
    else:
      d[i]=0
list(dict(sorted(d.items(),key=lambda x:x[1],reverse=True)).keys())

['456', '23fg', '1ac21', '1', 'kls', '098d']

`Problem 8:` Split String of list on K character.

**Example :**

Input:
```bash
['CampusX is a channel', 'for data-science', 'aspirants.']
```

Output:
```bash
['CampusX', 'is', 'a', 'channel', 'for', 'data-science', 'aspirants.']
```

In [ ]:
list1 = ['CampusX is a channel', 'for data-science', 'aspirants']
new_list=[]
for i in list1:
  for j in i.split(' '):
    new_list.append(j)
print(new_list)

['CampusX', 'is', 'a', 'channel', 'for', 'data-science', 'aspirants']

### `Problem 9:` Convert Character Matrix to single String using string comprehension.

**Example 1:**

Input:
```bash
[['c', 'a', 'm', 'p', 'u', 'x'], ['i', 's'], ['b', 'e', 's', 't'], ['c', 'h', 'a', 'n', 'n', 'e', 'l']]
```

Output:
```bash
campux is best channel
```

In [5]:
list1 = [['c', 'a', 'm', 'p', 'u', 'x'], ['i', 's'], ['b', 'e', 's', 't'], ['c', 'h', 'a', 'n', 'n', 'e', 'l']]
[''.join(i) for i in list1]

['campux', 'is', 'best', 'channel']

In [1]:
list1 = [['c', 'a', 'm', 'p', 'u', 'x'], ['i', 's'], ['b', 'e', 's', 't'], ['c', 'h', 'a', 'n', 'n', 'e', 'l']]
new_list=[]
for i in list1:
  new_list.append(''.join(i))
' '.join(new_list)

'campux is best channel'

### `Problem 10:` Add Space between Potential Words.

**Example:**

Input:

```bash
['campusxIs', 'bestFor', 'dataScientist']
```

Output:
```bash
['campusx Is', 'best For', 'data Scientist']
```

In [ ]:
list1 = ['campusxIs', 'bestFor', 'dataScientist']
new_list=[]
for i in list1:
  for k,j in enumerate(i):
    if j==j.upper():
      new_str=i[:k] + ' ' + i[k:]
      break
  new_list.append(new_str)
new_list

['campusx Is', 'best For', 'data Scientist']

### `Problem 11:` Write a program that can perform union operation on 2 lists

**Example:**

Input:

```bash
[1,2,3,4,5,1]
[2,3,5,7,8]
```

Output:
```bash
[1,2,3,4,5,7,8]
```

In [15]:
l=list1+list2     ### Understand this standard logic to get unique things from iterable
new_l=[]
for i in l:
  if i not in new_l:
    new_l.append(i)
new_l

[1, 2, 3, 4, 5, 7, 8]

In [6]:
list1 = [1,2,3,4,5,1]
list2 = [2,3,5,7,8]
new_list=[]
for i in list1:
  for j in list2:
    if i==j:
      new_list.append(i)
for i in list1:
  if i not in new_list:
    new_list.append(i)
for k in list2:
  if k not in new_list:
    new_list.append(k)
sorted(new_list)

[1, 2, 3, 4, 5, 7, 8]

### `Problem 12:` Write a program that can find the max number of each row of a matrix

**Example:**

Input:

```bash
[[1,2,3],[4,5,6],[7,8,9]]
```

Output:
```bash
[3,6,9]
```

In [ ]:
list1=[[1,2,3],[4,5,6],[7,8,9]]
new_list=[]
for i in list1:
  new_list.append(max(i))
new_list

[3, 6, 9]

## ***### `Problem 13:` Write a list comprehension to print the following matrix***

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [16]:
for i in range(3):
  for j in range(3*i,3*(i+1)):
    print(j,end=' ')
  print()

0 1 2
3 4 5
6 7 8

In [17]:
matrix = [[j for j in range(i-2, i+1)] for i in [2, 5, 8]]
print(matrix)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

### `Problem 14:` Write a list comprehension that can transpose a given matrix

matrix = [<br>
  [1,2,3],<br>
          [4,5,6],<br>
          [7,8,9]<br>]<br>

[1, 4, 7]<br>
[2, 5, 8]<br>
[3, 6, 9]<br>

In [ ]:
matrix = [
[1,2,3],
[4,5,6],
[7,8,9]
]

matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

### `Problem 15:` Write a list comprehension that can flatten a nested list

Input<br>
matrix = [<br>
  [1,2,3],<br>
          [4,5,6],<br>
          [7,8,9]<br>]<br>

Output:<br>
[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
matrix = [
[1,2,3],
[4,5,6],
[7,8,9]
]
[j for i in matrix for j in i]

[1, 2, 3, 4, 5, 6, 7, 8, 9]